apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: default
  labels:
    app: nexus
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: nexus-ui
    nodePort: 30081
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: nexus-docker
    nodePort: 30500
  selector:
    app: nexus

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-docker-registry
  namespace: default
  labels:
    app: nexus-docker-registry
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: docker-registry
  selector:
    app: nexus

