kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."nexus-docker-registry.default.svc.cluster.local:5000"]
        endpoint = ["http://nexus-docker-registry.default.svc.cluster.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus-docker-registry.default.svc.cluster.local:5000"]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."nexus-docker-registry.default.svc.cluster.local:5000".tls]
          insecure_skip_verify = true

